[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[cursor.style]
blinking = "On"
shape = "Beam"

[window]
blur = true
decorations = "full"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[keyboard]
